routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    Route::group(['namespace' => 'Receipt'], function() {
        Route::resource('faculty', 'FacultyController');
        Route::delete('faculties/destroy', 'FacultyController@massDestroy')->name('faculty.massDestroy');

        Route::get('programs/getspecificprograms','ProgramsController@getPrograms')->name('programs.getspecificprograms');
        Route::post('programs/addprogram','ProgramsController@addProgram')->name('programs.addProgram');
        Route::delete('programs/destroy', 'ProgramsController@massDestroy')->name('programs.massDestroy');
        Route::resource('programs', 'ProgramsController');

        Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
        Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
        Route::resource('programtypes', 'ProgramTypesController');

        Route::get('courses/getspecificcourses','CoursesController@getCourses')->name('courses.getspecificcourses');
        Route::get('courses/getcoursetypes','CoursesController@getCourseTypes')->name('courses.getcoursetypes');
        Route::delete('courses/destroy', 'CoursesController@massDestroy')->name('courses.massDestroy');
        Route::resource('courses', 'CoursesController');

        Route::get('batches/getspecificbatches','BatchesController@getBatches')->name('batches.getspecificbatches');
        Route::delete('batches/destroy', 'BatchesController@massDestroy')->name('batches.massDestroy');
        Route::resource('batches', 'BatchesController');

        Route::get('fees/dividetypes','FeesController@divideTypes')->name('fees.divideTypes');
        Route::delete('fees/destroy', 'FeesController@massDestroy')->name('fees.massDestroy');
        Route::resource('fees', 'FeesController');

        Route::delete('students/destroy', 'StudentsController@massDestroy')->name('students.massDestroy');
        Route::resource('students', 'StudentsController');

        Route::delete('fines/destroy', 'FinesController@massDestroy')->name('fines.massDestroy');
        Route::resource('fines', 'FinesController');

        Route::delete('payments/destroy', 'PaymentsController@massDestroy')->name('payments.massDestroy');
        Route::resource('payments', 'PaymentsController');
        Route::get('receipts', 'PaymentsController@allReceipts')->name('payments.allReceipts');
        Route::get('receipts/{receipt}', 'PaymentsController@generateReceipt')->name('payments.generateReceipt');

        Route::get('receipts/{receipt}/print', 'PaymentsController@printReceipt')->name('receipt-print');
    });
});

app/Http/Controllers/Receipt/CoursesController.php
<?php

namespace App\Http\Controllers\Receipt;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\Program;
use App\Models\Faculty;
use App\Models\ProgramType;
use Gate;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\Receipt\StoreCourseRequest;
use App\Http\Requests\Receipt\UpdateCourseRequest;
use App\Http\Requests\Receipt\MassDestroyCourseRequest;
use Session;
use Auth;

class CoursesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    //
    public function index()
    {
       
        abort_if(Gate::denies('course-access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $groups = Auth::user()->groups()->pluck('title');
        $courses = [];
        // dd($groups);
        //getting only accessible courses for user group
        foreach($groups as $key => $group){
            if($group == 'Owner'){
                $courses = Course::all();
                break;
            }
            else{
                $courses_under_faculty[$key] = Course::whereHas('faculty', function ($query) use ($group) {
                    $query->where('name',$group);
                    })->get();
            }
        }

        //converting multidimentional array of courses to single in order to return to view
        if(isset($courses_under_faculty) && !empty($courses_under_faculty)){
            foreach($courses_under_faculty as $course){
                foreach($course as $c){
                    $courses[] = $c;
                }
            }
        }
        return view('admin.backend.courses.index', compact('courses'));
    }

    public function create()
    {
        
        abort_if(Gate::denies('course-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');       
        $faculties = Faculty::all()->pluck('name','id');
        $programtypes = ProgramType::all()->pluck('name','id');
        $groups = Auth::user()->groups;
        // foreach($groups as $g){
        //     dd($g);
        // }
        return view('admin.backend.courses.create',compact('faculties','programtypes','groups'));
    }

    public function store(StoreCourseRequest $request)
    {
        // dd($request->all());
        $data=[
            'name' => $request->name,
            'abbreviation' => $request->abbreviation,
            'duration' => $request->duration,
            'description' => $request->description,
            'slug' => str_slug($request->name),
            'faculty_id' => $request->faculty_id,
            'program_id' => $request->program_id,
            'created_by' => Auth::user()->name,
        ];
        $max_weight = Course::pluck('weight')->max();

            if($request['weight'] == null){

                $data['weight'] = $max_weight + 10;
            }
        // dd($data);
        $course = Course::create($data);        
        $course->coursetypes()->sync($request->input('programtypes', []));

        Session::flash('flash_success', 'course created successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.courses.index');

    }

    public function edit(Course $course)
    {
        abort_if(Gate::denies('course-edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $faculties = Faculty::all()->pluck('name','id');
        $programtypes = ProgramType::all()->pluck('name','id');
        $groups = Auth::user()->groups;
        $course->load(['faculty','program','coursetypes']);
        $faculty_id = $course->faculty_id;
        $programs = Program::whereHas('faculties' , function ($query) use ($faculty_id)
                                {
                                    $query->where('faculty_id', $faculty_id);
                                })
                                ->with('faculties')
                                ->pluck('name','id');

        // dd($programs);
        return view('admin.backend.courses.edit', compact('course','faculties','programs','programtypes','groups'));
    }

    public function update(UpdateCourseRequest $request, Course $course)
    {
    //  dd($request);
        $data=[
            'name' => $request->name,
            'abbreviation' => $request->abbreviation,
            'duration' => $request->duration,
            'description' => $request->description,
            'slug' => str_slug($request->name),
            'faculty_id' => $request->faculty_id,
            'program_id' => $request->program_id,
            'created_by' => Auth::user()->name,
        ];
        
        // dd($data);
        $course->update($data);
        $course->coursetypes()->sync($request->input('programtypes', []));

        Session::flash('flash_success', 'course updated successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.courses.index');

    }

    public function show(Course $course)
    {
        abort_if(Gate::denies('course-show'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $course->load('coursetypes');
        return view('admin.backend.courses.show', compact('course'));
    }

    public function destroy(Course $course)
    {
        abort_if(Gate::denies('course-delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $course->delete();

        Session::flash('flash_danger', 'course has been deleted !.');
        Session::flash('flash_type', 'alert-danger');
        return back();

    }

    public function massDestroy(MassDestroyCourseRequest $request)
    {
        // dd($request);
        Course::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

    public function getCourses(Request $request)
    {
        $program_id = $request->programId;
        $faculty_id = $request->facultyId;
        // dd($faculty_id);
        $courses = Course::where([
                                    ['program_id',$program_id ], 
                                    ['faculty_id',$faculty_id]
                                ])->get();
        // dd($courses);
        return $courses;

    }

    public function getCourseTypes(Request $request)
    {
        $course_id = $request->courseId;
        $courses = Course::with('coursetypes')->find($course_id);
        return $courses;

    }
}

resources/views/admin/backend/courses/create.blade.php
@extends('admin.backend.layouts.master')
@section('title','Add Course')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.course.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.courses.store") }}" enctype="multipart/form-data">
            
            @csrf

            <div class="form-group">
                <label class="required" for="faculties">{{ trans('cruds.course.fields.faculty') }}</label>
                
                <select class="form-control {{ $errors->has('faculties') ? 'is-invalid' : '' }}" name="faculty_id" id="faculties" required>
                    @foreach($groups as $key => $group)
                    
                        @if($group->title == 'Owner')
                            <option value="0">Select a faculty...</option>
                            @foreach($faculties as $id => $faculty)
                                <option value="{{ $id }}" {{ in_array($id, old('faculty', [])) ? 'selected' : '' }}>{{ $faculty }}</option>
                            @endforeach
                            @break;

                        @elseif($group->title == 'Arts')
                            @foreach($faculties as $id => $faculty)
                                @if($faculty == 'Arts')
                                    <option value="{{ $id }}" {{ in_array($id, old('faculty', [])) ? 'selected' : '' }}>{{ $faculty }}</option>
                                @endif
                            @endforeach
                        
                        @elseif($group->title == 'Education')
                            @foreach($faculties as $id => $faculty)
                                @if($faculty == 'Education')
                                    <option value="{{ $id }}" {{ in_array($id, old('faculty', [])) ? 'selected' : '' }}>{{ $faculty }}</option>
                                @endif
                            @endforeach
                        @endif
                    @endforeach
                </select>
                @if($errors->has('faculty_id'))
                    <span class="text-danger">{{ $errors->first('faculty_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.faculty_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="programs">{{ trans('cruds.course.fields.program') }}</label>
                
                <select class="form-control {{ $errors->has('programs') ? 'is-invalid' : '' }}" name="program_id" id="programs" required>
                    <option value="0">Select a program...</option>
                 
                </select>
                @if($errors->has('programs'))
                    <span class="text-danger">{{ $errors->first('programs') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.program_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.course.fields.title') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.title_helper') }}</span>
                
            </div>

            <div class="form-group">
                <label class="required" for="abbreviation">{{ trans('cruds.course.fields.abbreviation') }}</label>
                <input class="form-control {{ $errors->has('abbreviation') ? 'is-invalid' : '' }}" type="text" name="abbreviation" id="abbreviation" value="{{ old('abbreviation', '') }}">
                @if($errors->has('abbreviation'))
                    <span class="text-danger">{{ $errors->first('abbreviation') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.abbreviation_helper') }}</span>
                
            </div>

            <div class="form-group">
                <label class="required" for="duration">{{ trans('cruds.course.fields.duration') }} (in Year)</label>
                <input class="form-control {{ $errors->has('duration') ? 'is-invalid' : '' }}" type="number" name="duration" id="duration" value="{{ old('duration', '') }}">
                @if($errors->has('duration'))
                    <span class="text-danger">{{ $errors->first('duration') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.duration_helper') }}</span>
                
            </div>

            <div class="form-group">
                <label class="required" for="programtypes">{{ trans('cruds.course.fields.coursetypes') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <div class="row">
                    <div class="col-md-11 row">
                        <select class="form-control select2 {{ $errors->has('programtypes') ? 'is-invalid' : '' }}" name="programtypes[]" id="programtypes" multiple required>
                            @foreach($programtypes as $id => $programtypes)
                                <option value="{{ $id }}" {{ in_array($id, old('programtypes', [])) ? 'selected' : '' }}>{{ $programtypes }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-1 row">
                        <a class="btn btn-success btn-md" data-toggle='modal' data-target="#addCourse" style="cursor:pointer;">
                                <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                @if($errors->has('programtypes'))
                    <span class="text-danger">{{ $errors->first('programtypes') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.coursetypes_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="description">{{ trans('cruds.course.fields.description') }}</label>
                
                <textarea class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" 
                                        style="width: 100%; height: 300px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="editor">{{ old('description', '') }}</textarea>
                            
                @if($errors->has('description'))
                    <span class="text-danger">{{ $errors->first('description') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.course.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.courses.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>

{{-- modal box for adding course types --}}
<div class="modal fade" id="addCourse">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{trans('global.add')}} {{ trans('cruds.programtype.title') }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">    
                    <div class="box-body">        
                        <div class="form-group">
                            <label class="required" for="name">{{ trans('cruds.programtype.fields.title') }}</label>
                            <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="type_name" value="{{ old('name', '') }}" required>
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.programtype.fields.title_helper') }}</span>
                            
                        </div>
                        <div class="form-group">
                            <label class="required" for="description">{{ trans('cruds.programtype.fields.description') }}</label>
                            {{-- <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', '') }}" required> --}}
                            <textarea class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" 
                                                    style="width: 100%; height: 300px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="description">{{ old('description', '') }}</textarea>
                                        
                            @if($errors->has('description'))
                                <span class="text-danger">{{ $errors->first('description') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.programtype.fields.title_helper') }}</span>
                        </div>
                        <!--form control-->
                    </div>
                </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id="addCourseType">Ok</button>
            </div>
        </div>
       
    </div>

</div>

@endsection

@section('scripts')
    {{-- get programs of specific faculty --}}
    <script>
        $(document).ready(function(){
            var faculty_id = $("#faculties").val();

        // if faculty is already selected
            if(faculty_id != 0){
                $.ajax({
                    cache:false,
                    url: '{{ route('admin.programs.getspecificprograms') }}',
                    type: 'get',
                    data: {facultyId:faculty_id},
                    dataType: 'json',
                    beforeSend: function(request) {
                                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                                    },
                    success:function(data){
                        var len = data.length;
                        $("#programs").empty();
                        for( var i = 0; i<len; i++){
                            var id = data[i]['id'];
                            var name = data[i]['name'];
                            $("#programs").append("<option value='"+id+"'>"+name+"</option>");
                        }
                    }
                });
            }

        // if changes is made on faculty selection
            $("#faculties").change(function(){
                var selected_id = $(this).val();
                $.ajax({
                    cache:false,
                    url: '{{ route('admin.programs.getspecificprograms') }}',
                    type: 'get',
                    data: {facultyId:selected_id},
                    dataType: 'json',
                    beforeSend: function(request) {
                                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                                    },
                    success:function(data){
                        var len = data.length;
                        $("#programs").empty();
                        for( var i = 0; i<len; i++){
                            var id = data[i]['id'];
                            var name = data[i]['name'];
                            $("#programs").append("<option value='"+id+"'>"+name+"</option>");
                        }
                    }
                });
            });
       

        $('#addCourseType').click(function(){
            var type_name = $('#type_name').val();
            var description =  $('#description').val();
            var type_data={
                        name: type_name,
                        description: description
                    };
            console.log(type_data);
            $.ajax({
               data:{data: type_data},
               url: "{{route('admin.programtypes.addType')}}",
               type: 'POST',
               beforeSend: function (request) {
                            return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                        },
                success: function (data){
                    console.log(data);
                    location.reload();  
                }
            });
        });
    }); 
    </script>
@endsection

resources/views/admin/backend/courses/index.blade.php
@extends('admin.backend.layouts.master')
@section('title','Course')

@section('content')
@can('course-create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary" href="{{ route("admin.courses.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.course.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.course.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Course">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.course.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.course.fields.title') }}
                        </th>
                        
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($courses as $key => $course)
                        <tr data-entry-id="{{ $course->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->index + 1 ?? '' }}
                            </td>
                            <td>
                                {{ $course->name ?? '' }}
                            </td>
                           
                            <td>
                                @can('course-show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.courses.show', $course->slug) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('course-edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.courses.edit', $course->slug) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('course-delete')
                                    <form action="{{ route('admin.courses.destroy', $course->slug) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection


@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('course-delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.courses.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': $('meta[name="csrf-token"]').attr('content')},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Course:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection