routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    Route::group(['namespace' => 'Receipt'], function() {
        Route::resource('faculty', 'FacultyController');
        Route::delete('faculties/destroy', 'FacultyController@massDestroy')->name('faculty.massDestroy');

        Route::get('programs/getspecificprograms','ProgramsController@getPrograms')->name('programs.getspecificprograms');
        Route::post('programs/addprogram','ProgramsController@addProgram')->name('programs.addProgram');
        Route::delete('programs/destroy', 'ProgramsController@massDestroy')->name('programs.massDestroy');
        Route::resource('programs', 'ProgramsController');

        Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
        Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
        Route::resource('programtypes', 'ProgramTypesController');

        Route::get('courses/getspecificcourses','CoursesController@getCourses')->name('courses.getspecificcourses');
        Route::get('courses/getcoursetypes','CoursesController@getCourseTypes')->name('courses.getcoursetypes');
        Route::delete('courses/destroy', 'CoursesController@massDestroy')->name('courses.massDestroy');
        Route::resource('courses', 'CoursesController');

        Route::get('batches/getspecificbatches','BatchesController@getBatches')->name('batches.getspecificbatches');
        Route::delete('batches/destroy', 'BatchesController@massDestroy')->name('batches.massDestroy');
        Route::resource('batches', 'BatchesController');

        Route::get('fees/dividetypes','FeesController@divideTypes')->name('fees.divideTypes');
        Route::delete('fees/destroy', 'FeesController@massDestroy')->name('fees.massDestroy');
        Route::resource('fees', 'FeesController');

        Route::delete('students/destroy', 'StudentsController@massDestroy')->name('students.massDestroy');
        Route::resource('students', 'StudentsController');

        Route::delete('fines/destroy', 'FinesController@massDestroy')->name('fines.massDestroy');
        Route::resource('fines', 'FinesController');

        Route::delete('payments/destroy', 'PaymentsController@massDestroy')->name('payments.massDestroy');
        Route::resource('payments', 'PaymentsController');
        Route::get('receipts', 'PaymentsController@allReceipts')->name('payments.allReceipts');
        Route::get('receipts/{receipt}', 'PaymentsController@generateReceipt')->name('payments.generateReceipt');

        Route::get('receipts/{receipt}/print', 'PaymentsController@printReceipt')->name('receipt-print');
    });
});

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Permission extends Model
{
    //
    use SoftDeletes;

    protected $dates = [
      'created_at',
      'updated_at',
      'deleted_at',
  ];
  
    protected $fillable = [
      'title',
      'slug',
      'created_at',
      'updated_at',
      'deleted_at',
  ];

    public function roles() {

        return $this->belongsToMany(Role::class,'roles_permissions');
            
     }
     
     public function admins() {
     
        return $this->belongsToMany(Admin::class,'admins_permissions');
            
     }

     public function getRouteKeyName() {
       
          return 'slug';
      }
}

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Permission;
use Gate;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\StorePermissionRequest;
use App\Http\Requests\UpdatePermissionRequest;
use App\Http\Requests\MassDestroyPermissionRequest;
use Session;

class PermissionsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    //
    public function index()
    {
       
        abort_if(Gate::denies('permission-access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $permissions = Permission::all();

        return view('admin.backend.permissions.index', compact('permissions'));
    }

    public function create()
    {
        abort_if(Gate::denies('permission-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.backend.permissions.create');
    }

    public function store(StorePermissionRequest $request)
    {
        // dd($request->all());
        $titles = $request->title;
        foreach($titles as $title){

            $data=[
                'title' => $title,
                'slug' => str_slug($title)
            ];
            // dd($data);
            $permission = Permission::create($data);
        }

        Session::flash('flash_success', 'Permission created successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.permissions.index');

    }

    public function edit(Permission $permission)
    {
        abort_if(Gate::denies('permission-edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.backend.permissions.edit', compact('permission'));
    }

    public function update(UpdatePermissionRequest $request, Permission $permission)
    {
        // dd($request);
        $data=[
            'title' => $request->title,
            'slug' => str_slug($request->title)
        ];
        // dd($data);
        $permission->update($data);

        Session::flash('flash_success', 'Permission updated successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.permissions.index');

    }

    public function show(Permission $permission)
    {
        abort_if(Gate::denies('permission-show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.backend.permissions.show', compact('permission'));
    }

    public function destroy(Permission $permission)
    {
        abort_if(Gate::denies('permission-delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $permission->delete();

        Session::flash('flash_danger', 'Permission has been deleted !.');
        Session::flash('flash_type', 'alert-danger');
        return back();

    }

    public function massDestroy(MassDestroyPermissionRequest $request)
    {
        Permission::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }
}

resources/views/admin/backend/permissions/create.blade.php
@extends('admin.backend.layouts.master')
@section('title','Add Permission')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.permission.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.permissions.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group dynamic_field">
                <label class="required" for="title">{{ trans('cruds.permission.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title[]" id="title" value="{{ old('title', '') }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.permission.fields.title_helper') }}</span>
            </div>
            <p id="add" style="color:#3B3B98; cursor:pointer;"> Click me to add more permission</p>
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.permissions.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){    
            //adding permissions dynamically
            var i = 1;
            $('#add').click(function(){
                i++;
                $('.dynamic_field').append('<div class="row" id="row'+i+'" style="padding:5px;"> <div class="col-md-11"><input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title[]" id="title" value="{{ old('title', '') }}" required> </div> <div class="col-md-1"> <input type="button" id="'+i+'" class="btn btn-danger remove" value="X"> </div> </div>');
                // <div class="col-md-12 row" id="row'+i+'" style="padding:5px;"> <div class="col-md-10"> <input type="text" class="form-control is-warning" name="options[]" id="options" placeholder="Enter Options..." required> </div> <div class="col-md-1"> <span><i class="fas fa-book"></i></span> </div> <div class="col-md-1"> <input type="button" id="'+i+'" class="btn btn-danger remove" value="X"> </div> </div>
                
                // @if($errors->has('title'))
                //     <span class="text-danger">{{ $errors->first('title') }}</span>
                // @endif
                // <span class="help-block">{{ trans('cruds.permission.fields.title_helper') }}</span>
            });
            

            $('body').on('click','.remove',function(){
                var button_id = $(this).attr("id");
                $('#row'+button_id+'').remove();
            });

        });
    </script>
@endsection

resources/views/admin/backend/permissions/edit.blade.php
@extends('admin.backend.layouts.master')
@section('title','Edit Permission')

@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.permission.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.permissions.update", [$permission->slug]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('cruds.permission.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $permission->title) }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.permission.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.permissions.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/backend/permissions/index.blade.php
@extends('admin.backend.layouts.master')
@section('title','Permission')

@section('content')
@can('permission-create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary" href="{{ route("admin.permissions.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.permission.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.permission.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.permission.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.permission.fields.title') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($permissions as $key => $permission)
                        <tr data-entry-id="{{ $permission->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->index + 1 ?? '' }}
                            </td>
                            <td>
                                {{ $permission->title ?? '' }}
                            </td>
                            <td>
                                @can('permission-show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.permissions.show', $permission->slug) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('permission-edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.permissions.edit', $permission->slug) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('permission-delete')
                                    <form action="{{ route('admin.permissions.destroy', $permission->slug) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection


@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('permission-delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.permissions.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': $('meta[name="csrf-token"]').attr('content')},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Permission:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/backend/permissions/show.blade.php
@extends('admin.backend.layouts.master')
@section('title','View Permission')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.permission.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            
            <table class="table table-bordered table-striped">
                <tbody>
                   
                    <tr>
                        <th>
                            {{ trans('cruds.permission.fields.title') }}
                        </th>
                        <td>
                            {{ $permission->title }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.permissions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection